use crate::paths::Paths;
use crate::state::Lockfile;
use anyhow::{Context, Result};

/// Generate `<env_root>/_index.md` from the lockfile contents.
/// The file starts with `<!-- generated by rdc; do not edit -->` so users know
/// to regenerate via `rdc pull` rather than editing by hand.
///
/// Sections (M28):
/// - Inventory: per-kind counts.
/// - Per-kind object listings (slug + id).
/// - Cross-references: forward refs from hooks/rules/email_templates to
///   the queue(s) they're attached to (resolved via lockfile slug_for_url).
///   Helps AI/humans navigate without parsing every JSON.
pub fn generate(paths: &Paths, lockfile: &Lockfile) -> Result<()> {
    let env_root = paths.env_root();
    if !env_root.exists() {
        return Ok(());
    }

    let mut md = String::new();
    md.push_str("<!-- generated by rdc; do not edit -->\n");
    md.push_str(&format!("# {}\n\n", paths.env()));
    md.push_str("This file is regenerated on every `rdc pull`. Edit the snapshot files, not this index.\n\n");
    md.push_str("## Inventory\n\n");

    let preferred = [
        "organization",
        "workspaces",
        "queues",
        "schemas",
        "inboxes",
        "hooks",
        "rules",
        "labels",
        "engines",
        "engine_fields",
        "workflows",
        "workflow_steps",
        "email_templates",
        "mdh_collections",
        "mdh_indexes",
    ];

    let mut emitted: std::collections::HashSet<&str> = std::collections::HashSet::new();
    for kind in preferred {
        if let Some(entries) = lockfile.objects.get(kind) {
            md.push_str(&format!("- {}: {}\n", kind, entries.len()));
            emitted.insert(kind);
        }
    }
    for (kind, entries) in lockfile.objects.iter() {
        if !emitted.contains(kind.as_str()) {
            md.push_str(&format!("- {}: {}\n", kind, entries.len()));
        }
    }
    md.push('\n');

    for kind in preferred {
        if let Some(entries) = lockfile.objects.get(kind) {
            md.push_str(&format!("## {}\n\n", kind));
            for (slug, entry) in entries.iter() {
                if entry.id == 0 {
                    md.push_str(&format!("- `{}`\n", slug));
                } else {
                    md.push_str(&format!("- `{}` (id {})\n", slug, entry.id));
                }
            }
            md.push('\n');
        }
    }

    // Cross-references (M28): forward refs from writable kinds to queues.
    // Best-effort: silently skip files we can't parse or refs we can't
    // resolve (e.g. orphan queues that were skipped during pull).
    append_cross_references(&mut md, paths, lockfile);

    let path = env_root.join("_index.md");
    crate::snapshot::writer::write_atomic(&path, md.as_bytes())
        .with_context(|| format!("writing {}", path.display()))?;

    Ok(())
}

fn append_cross_references(md: &mut String, paths: &Paths, lockfile: &Lockfile) {
    let mut sections = Vec::<String>::new();

    // hooks → queues
    if let Some(s) = build_multi_queue_refs(paths.hooks_dir(), lockfile, "queues") {
        sections.push(format!("### hooks → queues\n\n{}", s));
    }
    // rules → queues
    if let Some(s) = build_multi_queue_refs(paths.rules_dir(), lockfile, "queues") {
        sections.push(format!("### rules → queues\n\n{}", s));
    }
    // email_templates → queue (single).
    if let Some(s) = build_email_template_refs(paths, lockfile) {
        sections.push(format!("### email_templates → queue\n\n{}", s));
    }

    if sections.is_empty() {
        return;
    }
    md.push_str("## Cross-references\n\n");
    for section in sections {
        md.push_str(&section);
        md.push('\n');
    }
}

/// Walk a flat-list dir (hooks/, rules/) and produce lines of the form
/// `- <slug> → <queue-slug>, <queue-slug>`. Each object's queue refs
/// come from a JSON array field named `<field>` (typically "queues").
/// Resolves URLs to slugs via lockfile.slug_for_url("queues", ...).
fn build_multi_queue_refs(
    dir: std::path::PathBuf,
    lockfile: &Lockfile,
    field: &str,
) -> Option<String> {
    if !dir.exists() {
        return None;
    }
    let entries = std::fs::read_dir(&dir).ok()?;
    let mut lines: Vec<(String, String)> = Vec::new();
    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().to_string();
        let Some(slug) = name.strip_suffix(".json") else { continue };
        if slug.ends_with(".remote") {
            continue;
        }
        let raw = std::fs::read_to_string(entry.path()).ok()?;
        let v: serde_json::Value = serde_json::from_str(&raw).ok()?;
        let urls = v.get(field).and_then(|x| x.as_array());
        let queue_slugs = match urls {
            Some(arr) => arr
                .iter()
                .filter_map(|u| u.as_str())
                .filter_map(|u| lockfile.slug_for_url("queues", u))
                .collect::<Vec<_>>(),
            None => Vec::new(),
        };
        let rendered = if queue_slugs.is_empty() {
            "(none)".to_string()
        } else {
            queue_slugs.join(", ")
        };
        lines.push((slug.to_string(), rendered));
    }
    if lines.is_empty() {
        return None;
    }
    lines.sort();
    let mut out = String::new();
    for (slug, qs) in lines {
        out.push_str(&format!("- `{slug}` → {qs}\n"));
    }
    Some(out)
}

/// Email templates live nested under each queue. The natural cross-ref is
/// "this template belongs to that queue" — the lockfile key is already
/// `<ws>/<q>/<template>` so the queue slug is the middle segment.
fn build_email_template_refs(paths: &Paths, lockfile: &Lockfile) -> Option<String> {
    let entries = lockfile.objects.get("email_templates")?;
    if entries.is_empty() {
        return None;
    }
    // Filter to entries that actually exist on disk so we don't list stale
    // lockfile entries.
    let workspaces_dir = paths.workspaces_dir();
    let mut lines: Vec<String> = Vec::new();
    for key in entries.keys() {
        let mut parts = key.splitn(3, '/');
        let (ws, q, t) = match (parts.next(), parts.next(), parts.next()) {
            (Some(ws), Some(q), Some(t)) if !ws.is_empty() && !q.is_empty() && !t.is_empty()
                => (ws, q, t),
            _ => continue,
        };
        let path = paths.queue_email_templates_dir(ws, q).join(format!("{t}.json"));
        if !path.exists() {
            continue;
        }
        // Sanity-check that the queue slug is in the lockfile (skip orphans).
        if !workspaces_dir.exists() {
            continue;
        }
        if lockfile.objects.get("queues").map(|m| m.contains_key(q)).unwrap_or(false) {
            lines.push(format!("- `{key}` → `{q}`\n"));
        }
    }
    if lines.is_empty() {
        return None;
    }
    lines.sort();
    Some(lines.concat())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::ObjectEntry;

    #[test]
    fn generate_writes_index_file() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        std::fs::create_dir_all(paths.env_root()).unwrap();

        let mut lf = Lockfile::default();
        lf.upsert("hooks", "validator", ObjectEntry {
            id: 1, url: None, modified_at: None, content_hash: None,
        });
        lf.upsert("hooks", "sftp-import", ObjectEntry {
            id: 2, url: None, modified_at: None, content_hash: None,
        });
        lf.upsert("rules", "validation", ObjectEntry {
            id: 3, url: None, modified_at: None, content_hash: None,
        });

        generate(&paths, &lf).unwrap();

        let body = std::fs::read_to_string(paths.env_root().join("_index.md")).unwrap();
        assert!(body.starts_with("<!-- generated by rdc; do not edit -->"));
        assert!(body.contains("# dev"));
        assert!(body.contains("- hooks: 2"));
        assert!(body.contains("- rules: 1"));
        assert!(body.contains("`validator` (id 1)"));
        assert!(body.contains("`sftp-import` (id 2)"));
        assert!(body.contains("`validation` (id 3)"));
    }

    #[test]
    fn generate_skips_when_env_root_missing() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "missing");
        let lf = Lockfile::default();
        generate(&paths, &lf).unwrap();
        assert!(!paths.env_root().exists());
    }

    #[test]
    fn cross_refs_resolve_hook_to_queue_via_lockfile_url() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        std::fs::create_dir_all(paths.hooks_dir()).unwrap();

        std::fs::write(
            paths.hooks_dir().join("validator.json"),
            r#"{"id":1,"url":"https://x/api/v1/hooks/1","name":"Validator",
"queues":["https://x/api/v1/queues/100"]}"#,
        ).unwrap();

        let mut lf = Lockfile::default();
        lf.upsert("hooks", "validator", ObjectEntry {
            id: 1,
            url: Some("https://x/api/v1/hooks/1".into()),
            modified_at: None, content_hash: None,
        });
        lf.upsert("queues", "cost-invoices", ObjectEntry {
            id: 100,
            url: Some("https://x/api/v1/queues/100".into()),
            modified_at: None, content_hash: None,
        });

        generate(&paths, &lf).unwrap();
        let body = std::fs::read_to_string(paths.env_root().join("_index.md")).unwrap();
        assert!(body.contains("## Cross-references"));
        assert!(body.contains("### hooks → queues"));
        assert!(body.contains("`validator` → cost-invoices"),
                "body should contain hook→queue line; body:\n{body}");
    }

    #[test]
    fn cross_refs_renders_none_when_hook_has_empty_queues() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        std::fs::create_dir_all(paths.hooks_dir()).unwrap();

        std::fs::write(
            paths.hooks_dir().join("orphan.json"),
            r#"{"id":1,"url":"https://x/api/v1/hooks/1","name":"Orphan","queues":[]}"#,
        ).unwrap();

        let mut lf = Lockfile::default();
        lf.upsert("hooks", "orphan", ObjectEntry {
            id: 1, url: Some("https://x/api/v1/hooks/1".into()),
            modified_at: None, content_hash: None,
        });

        generate(&paths, &lf).unwrap();
        let body = std::fs::read_to_string(paths.env_root().join("_index.md")).unwrap();
        assert!(body.contains("`orphan` → (none)"));
    }
}
