//! `_index.md` generator for a pulled env snapshot.
//!
//! Regenerated once at the end of every `rdc sync` cycle, right after the
//! lockfile is saved (`cli::sync::run`) — so it reflects the state both the
//! push and the pull phase left behind. It's the entry point for an agent
//! (Claude Code or similar) or a human dropping into the repo: every object
//! is listed with its slug, id, human name, and the facts and links that
//! cannot be found with a plain search.
//!
//! Design goals:
//! - **Short.** A large tenant has hundreds of objects, and an agent reads
//!   this file into its context. Every object is one line. The kinds that
//!   belong to one parent — schema, inbox, formulas, email templates, engine
//!   fields — are not listed: their paths follow from the parent's, and a
//!   listing of hundreds of field files tells a reader nothing a directory
//!   listing would not. Workflow steps are listed on the workflow's line,
//!   because their order is the point. MDH indexes are the one kind listed
//!   in detail, one sub-line per index, because their definition is what a
//!   reader needs to write a matching query.
//! - **Searchable.** A link is written once, on the line of the object that
//!   holds it (a hook names its queues; the queue does not name its hooks).
//!   Searching the file for a slug finds every line that names it, so no
//!   reverse links are emitted.
//! - **Paths by rule.** Every path follows from the slug, so the header
//!   states the rule once per kind present, relative to the project root.
//! - **Deterministic.** Same lockfile + same on-disk JSONs ⇒ byte-for-byte
//!   identical output. No timestamps in the body.
//! - **Best-effort.** Missing or unparseable JSON files are silently
//!   skipped; a fresh pull is what fully populates the index.

use crate::paths::Paths;
use crate::state::Lockfile;
use anyhow::{Context, Result};
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

/// Generate `<env_root>/_index.md` from the lockfile + on-disk JSONs.
pub fn generate(paths: &Paths, lockfile: &Lockfile) -> Result<()> {
    let env_root = paths.env_root();
    if !env_root.exists() {
        return Ok(());
    }

    let ctx = IndexCtx {
        paths,
        lockfile,
        queue_to_ws_slug: build_queue_to_ws(paths),
    };

    let mut md = String::new();
    md.push_str("<!-- generated by rdc; do not edit -->\n");
    md.push_str(&format!("# {}\n\n", paths.env()));
    md.push_str(
        "Every object in this env, one per line: `slug` (id) \"name\" · facts. \
         A link to another object is listed once, on the line of the object \
         that holds it — search this file for a slug to find everything that \
         names it. Regenerated on every `rdc sync`; edit the files, not this \
         index.\n\n",
    );
    emit_counts(&mut md, lockfile);
    emit_path_rules(&mut md, &ctx);

    // Outside in, so a reader builds context before the details.
    emit_organization(&mut md, &ctx);
    emit_queues(&mut md, &ctx);
    emit_hooks(&mut md, &ctx);
    emit_rules(&mut md, &ctx);
    emit_flat(&mut md, &ctx, "labels", "labels", &ctx.paths.labels_dir());
    emit_flat(&mut md, &ctx, "saved_views", "saved views", &ctx.paths.saved_views_dir());
    emit_engines(&mut md, &ctx);
    emit_workflows(&mut md, &ctx);
    emit_mdh_indexes(&mut md, &ctx);

    // Any other kinds we haven't modeled (mdh_data, future) get a terse
    // catch-all so they're at least listed.
    emit_unknown_kinds(&mut md, lockfile);

    // Every section ends with a blank separator line; the file ends with one
    // newline.
    let body = format!("{}\n", md.trim_end());
    let path = env_root.join("_index.md");
    crate::snapshot::writer::write_atomic(&path, body.as_bytes())
        .with_context(|| format!("writing {}", path.display()))?;

    Ok(())
}

/// Kinds with their own section, or folded into another kind's line. Used to
/// filter the catch-all section.
const KNOWN_KINDS: &[&str] = &[
    "organization",
    "workspaces",
    "queues",
    "schemas",
    "inboxes",
    "hooks",
    "rules",
    "labels",
    "saved_views",
    "engines",
    "engine_fields",
    "workflows",
    "workflow_steps",
    "email_templates",
    "mdh_indexes",
];

struct IndexCtx<'a> {
    paths: &'a Paths,
    lockfile: &'a Lockfile,
    /// queue_slug → workspace_slug (resolved by walking the disk layout)
    queue_to_ws_slug: BTreeMap<String, String>,
}

impl IndexCtx<'_> {
    fn has(&self, kind: &str) -> bool {
        self.lockfile
            .objects
            .get(kind)
            .is_some_and(|m| !m.is_empty())
    }
}

/// Walk `workspaces/<ws>/queues/<q>/` to learn each queue's parent
/// workspace. The disk layout is authoritative here — works even when
/// queue.json is missing or unparseable.
fn build_queue_to_ws(paths: &Paths) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    for ws_slug in subdirs(&paths.workspaces_dir()) {
        for q_slug in subdirs(&paths.queues_dir(&ws_slug)) {
            out.insert(q_slug, ws_slug.clone());
        }
    }
    out
}

// ----- Header ---------------------------------------------------------

/// One line of per-kind totals, so a reader knows how big the env is before
/// reading on. The organization is always one and says nothing.
fn emit_counts(md: &mut String, lockfile: &Lockfile) {
    let counts: Vec<String> = lockfile
        .objects
        .iter()
        .filter(|(kind, m)| kind.as_str() != "organization" && !m.is_empty())
        .map(|(kind, m)| format!("{} {kind}", m.len()))
        .collect();
    if !counts.is_empty() {
        md.push_str(&format!("Objects: {}.\n\n", counts.join(" · ")));
    }
}

/// Where each kind present lives on disk, relative to the project root. Stated
/// once here so no object line has to carry its own path.
fn emit_path_rules(md: &mut String, ctx: &IndexCtx<'_>) {
    let env = format!("envs/{}", ctx.paths.env());
    let mut rules = Vec::new();
    if ctx.has("organization") {
        rules.push(format!("organization: `{env}/organization.json`"));
    }
    if ctx.has("workspaces") || ctx.has("queues") {
        rules.push(format!(
            "workspace: `{env}/workspaces/<workspace>/workspace.json`; its queues in \
             `queues/<queue>/` — `queue.json`, `schema.json`, `inbox.json`, \
             `formulas/<field_id>.py`, `email-templates/<slug>.json`"
        ));
    }
    if ctx.has("hooks") {
        rules.push(format!(
            "hook: `{env}/hooks/<slug>.json`, code in `<slug>.py` or `<slug>.js`"
        ));
    }
    if ctx.has("rules") {
        rules.push(format!(
            "rule: `{env}/rules/<slug>.json`, trigger condition in `<slug>.py`"
        ));
    }
    if ctx.has("labels") {
        rules.push(format!("label: `{env}/labels/<slug>.json`"));
    }
    if ctx.has("saved_views") {
        rules.push(format!("saved view: `{env}/saved-views/<slug>.json`"));
    }
    if ctx.has("engines") {
        rules.push(format!(
            "engine: `{env}/engines/<engine>/engine.json`, its fields in `fields/<slug>.json`"
        ));
    }
    if ctx.has("workflows") {
        rules.push(format!(
            "workflow: `{env}/workflows/<workflow>/workflow.json`, its steps in `steps/<slug>.json`"
        ));
    }
    if ctx.has("mdh_indexes") || ctx.has("mdh_data") {
        rules.push(format!(
            "Master Data Hub dataset: `{env}/mdh/<dataset>/`, indexes in `indexes.json`"
        ));
    }
    if rules.is_empty() {
        return;
    }
    md.push_str("Paths:\n\n");
    for r in rules {
        md.push_str(&format!("- {r}\n"));
    }
    md.push('\n');
}

// ----- Per-kind sections ----------------------------------------------

fn emit_organization(md: &mut String, ctx: &IndexCtx<'_>) {
    let Some(entries) = ctx.lockfile.objects.get("organization") else {
        return;
    };
    let v = read_json(&ctx.paths.organization_file());
    for (slug, entry) in entries {
        md.push_str(&format!(
            "Organization: {}\n\n",
            entry_line(slug, entry.id, v.as_ref())
        ));
    }
}

/// Queues grouped under their workspace. The workspace heading replaces both
/// the old workspace section and each queue's `workspace:` line.
fn emit_queues(md: &mut String, ctx: &IndexCtx<'_>) {
    let empty = BTreeMap::new();
    let workspaces = ctx.lockfile.objects.get("workspaces").unwrap_or(&empty);
    let queues = ctx.lockfile.objects.get("queues").unwrap_or(&empty);
    if workspaces.is_empty() && queues.is_empty() {
        return;
    }

    let mut by_ws: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    let mut unplaced = Vec::new();
    for slug in queues.keys() {
        match ctx.queue_to_ws_slug.get(slug) {
            Some(ws) => by_ws.entry(ws.as_str()).or_default().push(slug),
            None => unplaced.push(slug.as_str()),
        }
    }
    let ws_slugs: BTreeSet<&str> = workspaces
        .keys()
        .map(String::as_str)
        .chain(by_ws.keys().copied())
        .collect();

    md.push_str("## queues\n\n");
    for ws in ws_slugs {
        let id = workspaces.get(ws).map_or(0, |e| e.id);
        let v = read_json(&ctx.paths.workspace_dir(ws).join("workspace.json"));
        md.push_str(&format!("### {}\n\n", entry_title(ws, id, v.as_ref())));
        if let Some(qs) = by_ws.get(ws) {
            for q in qs {
                md.push_str(&queue_line(ctx, ws, q, queues[*q].id));
            }
            md.push('\n');
        }
    }
    if !unplaced.is_empty() {
        md.push_str("### not on disk\n\n");
        for q in unplaced {
            md.push_str(&format!("{}\n", entry_line(q, queues[q].id, None)));
        }
        md.push('\n');
    }
}

fn queue_line(ctx: &IndexCtx<'_>, ws: &str, slug: &str, id: u64) -> String {
    let v = read_json(&ctx.paths.queue_dir(ws, slug).join("queue.json"));
    let mut line = entry_line(slug, id, v.as_ref());
    if let Some(e) = v
        .as_ref()
        .and_then(|v| url_to_slug(v, "engine", "engines", ctx.lockfile))
    {
        line.push_str(&format!(" · engine `{e}`"));
    }
    line.push('\n');
    line
}

fn emit_hooks(md: &mut String, ctx: &IndexCtx<'_>) {
    let Some(entries) = ctx.lockfile.objects.get("hooks").filter(|m| !m.is_empty()) else {
        return;
    };
    md.push_str("## hooks\n\n");
    for (slug, entry) in entries {
        let v = read_json(&ctx.paths.hooks_dir().join(format!("{slug}.json")));
        let mut line = entry_line(slug, entry.id, v.as_ref());
        if let Some(v) = v.as_ref() {
            if let Some(t) = v.get("type").and_then(Value::as_str) {
                line.push_str(&format!(" · {t}"));
            }
            // A disabled hook reads exactly like a live one in every other
            // respect, and is the first thing to rule out when one "does
            // nothing" — so it is the one flag worth a line's space.
            if v.get("active") == Some(&Value::Bool(false)) {
                line.push_str(" · **inactive**");
            }
            let events: Vec<&str> = v
                .get("events")
                .and_then(Value::as_array)
                .map(|a| a.iter().filter_map(Value::as_str).collect())
                .unwrap_or_default();
            if !events.is_empty() {
                line.push_str(&format!(" · on [{}]", events.join(", ")));
            }
            let after = urls_to_slugs(v, "run_after", "hooks", ctx.lockfile);
            if !after.is_empty() {
                line.push_str(&format!(" · after {}", join_slugs(&after)));
            }
            let qs = urls_to_slugs(v, "queues", "queues", ctx.lockfile);
            if !qs.is_empty() {
                line.push_str(&format!(" · queues {}", join_slugs(&qs)));
            }
        }
        md.push_str(&line);
        md.push('\n');
    }
    md.push('\n');
}

fn emit_rules(md: &mut String, ctx: &IndexCtx<'_>) {
    let Some(entries) = ctx.lockfile.objects.get("rules").filter(|m| !m.is_empty()) else {
        return;
    };
    md.push_str("## rules\n\n");
    for (slug, entry) in entries {
        let v = read_json(&ctx.paths.rules_dir().join(format!("{slug}.json")));
        let mut line = entry_line(slug, entry.id, v.as_ref());
        if let Some(v) = v.as_ref() {
            let qs = urls_to_slugs(v, "queues", "queues", ctx.lockfile);
            if !qs.is_empty() {
                line.push_str(&format!(" · queues {}", join_slugs(&qs)));
            }
        }
        md.push_str(&line);
        md.push('\n');
    }
    md.push('\n');
}

/// A kind stored as `<dir>/<slug>.json` with nothing worth showing but its
/// name.
fn emit_flat(md: &mut String, ctx: &IndexCtx<'_>, kind: &str, heading: &str, dir: &Path) {
    let Some(entries) = ctx.lockfile.objects.get(kind).filter(|m| !m.is_empty()) else {
        return;
    };
    md.push_str(&format!("## {heading}\n\n"));
    for (slug, entry) in entries {
        let v = read_json(&dir.join(format!("{slug}.json")));
        md.push_str(&entry_line(slug, entry.id, v.as_ref()));
        md.push('\n');
    }
    md.push('\n');
}

/// Engines only. Their fields are not listed: an engine can have hundreds,
/// and each is one file under the engine's dir.
fn emit_engines(md: &mut String, ctx: &IndexCtx<'_>) {
    let Some(entries) = ctx.lockfile.objects.get("engines").filter(|m| !m.is_empty()) else {
        return;
    };
    md.push_str("## engines\n\n");
    for (slug, entry) in entries {
        let v = read_json(&ctx.paths.engine_dir(slug).join("engine.json"));
        md.push_str(&entry_line(slug, entry.id, v.as_ref()));
        md.push('\n');
    }
    md.push('\n');
}

/// Workflows with their steps in order. A workflow has a handful of steps,
/// and their order is the point, so they are listed rather than counted.
fn emit_workflows(md: &mut String, ctx: &IndexCtx<'_>) {
    let Some(entries) = ctx.lockfile.objects.get("workflows").filter(|m| !m.is_empty()) else {
        return;
    };
    md.push_str("## workflows\n\n");
    for (slug, entry) in entries {
        let v = read_json(&ctx.paths.workflow_dir(slug).join("workflow.json"));
        let mut line = entry_line(slug, entry.id, v.as_ref());
        if let Some(v) = v.as_ref() {
            let steps = urls_to_slugs(v, "steps", "workflow_steps", ctx.lockfile);
            if !steps.is_empty() {
                line.push_str(&format!(" · steps {}", join_slugs(&steps)));
            }
        }
        md.push_str(&line);
        md.push('\n');
    }
    md.push('\n');
}

/// One sub-line per index, because the definition — which columns, in what
/// order, unique or not, which fields a search index maps — is what a reader
/// needs to write a query that uses it, and it is short.
fn emit_mdh_indexes(md: &mut String, ctx: &IndexCtx<'_>) {
    let Some(entries) = ctx
        .lockfile
        .objects
        .get("mdh_indexes")
        .filter(|m| !m.is_empty())
    else {
        return;
    };
    md.push_str("## mdh_indexes\n\n");
    for (slug, entry) in entries {
        md.push_str(&entry_line(slug, entry.id, None));
        md.push('\n');
        let Some(set) = read_json(&ctx.paths.dataset_dir(slug).join("indexes.json")) else {
            continue;
        };
        for ix in set.get("regular").and_then(Value::as_array).into_iter().flatten() {
            md.push_str(&format!("  - {}\n", regular_index_line(ix)));
        }
        for ix in set.get("search").and_then(Value::as_array).into_iter().flatten() {
            md.push_str(&format!("  - {}\n", search_index_line(ix)));
        }
    }
    md.push('\n');
}

/// `` `ix_name`: `col` asc, `other` desc · unique `` — key columns in index
/// order, then the options that change what the index matches.
fn regular_index_line(ix: &Value) -> String {
    let name = ix.get("name").and_then(Value::as_str).unwrap_or("?");
    let keys: Vec<String> = ix
        .get("key")
        .and_then(Value::as_object)
        .map(|k| {
            k.iter()
                .map(|(col, dir)| {
                    let dir = match dir.as_i64() {
                        Some(1) => "asc".to_string(),
                        Some(-1) => "desc".to_string(),
                        _ => dir.as_str().map_or_else(|| dir.to_string(), str::to_string),
                    };
                    format!("`{col}` {dir}")
                })
                .collect()
        })
        .unwrap_or_default();
    let mut line = format!("`{name}`: {}", keys.join(", "));
    for flag in ["unique", "sparse"] {
        if ix.get(flag) == Some(&Value::Bool(true)) {
            line.push_str(&format!(" · {flag}"));
        }
    }
    if let Some(filter) = ix.get("partialFilterExpression") {
        line.push_str(&format!(" · partial {}", code_span(&filter.to_string())));
    }
    if let Some(ttl) = ix.get("expireAfterSeconds").and_then(Value::as_i64) {
        line.push_str(&format!(" · expires after {ttl}s"));
    }
    if let Some(locale) = ix
        .get("collation")
        .and_then(|c| c.get("locale"))
        .and_then(Value::as_str)
    {
        line.push_str(&format!(" · collation `{locale}`"));
    }
    line
}

/// `` search `name`: `col` string, `addr.city` autocomplete · dynamic ·
/// analyzer `lucene.standard` `` — mapped fields with their types (nested
/// `document` fields as dotted paths), then the analyzers and synonyms.
fn search_index_line(ix: &Value) -> String {
    let name = ix.get("name").and_then(Value::as_str).unwrap_or("?");
    let mappings = ix.get("mappings");
    let mut fields = Vec::new();
    if let Some(f) = mappings.and_then(|m| m.get("fields")) {
        collect_search_fields("", f, &mut fields);
    }
    let mut line = format!("search `{name}`");
    if !fields.is_empty() {
        line.push_str(&format!(": {}", fields.join(", ")));
    }
    if mappings
        .and_then(|m| m.get("dynamic"))
        .is_some_and(|d| d != &Value::Bool(false))
    {
        line.push_str(" · dynamic");
    }
    for (key, label) in [("analyzer", "analyzer"), ("searchAnalyzer", "search analyzer")] {
        if let Some(a) = ix.get(key).and_then(Value::as_str) {
            line.push_str(&format!(" · {label} `{a}`"));
        }
    }
    for (key, label) in [("analyzers", "custom analyzers"), ("synonyms", "synonyms")] {
        let names: Vec<&str> = ix
            .get(key)
            .and_then(Value::as_array)
            .map(|a| a.iter().filter_map(|x| x.get("name")?.as_str()).collect())
            .unwrap_or_default();
        if !names.is_empty() {
            line.push_str(&format!(" · {label} {}", join_slugs(&names)));
        }
    }
    line
}

/// Flatten a search `mappings.fields` object into `` `path` type[/type] ``
/// entries. A field maps to one definition or an array of them; a
/// `document` / `embeddedDocuments` definition with its own `fields`
/// contributes its children as dotted paths.
fn collect_search_fields(prefix: &str, fields: &Value, out: &mut Vec<String>) {
    let Some(fields) = fields.as_object() else {
        return;
    };
    for (name, def) in fields {
        let path = format!("{prefix}{name}");
        let defs: Vec<&Value> = match def {
            Value::Array(a) => a.iter().collect(),
            other => vec![other],
        };
        let mut types = Vec::new();
        for d in &defs {
            match d.get("fields") {
                Some(children) => collect_search_fields(&format!("{path}."), children, out),
                None => {
                    if let Some(t) = d.get("type").and_then(Value::as_str) {
                        types.push(t);
                    }
                }
            }
        }
        if !types.is_empty() {
            out.push(format!("`{path}` {}", types.join("/")));
        }
    }
}

/// A value as an inline code span, truncated like a name so one large filter
/// cannot blow up the line.
fn code_span(s: &str) -> String {
    const MAX: usize = 120;
    if s.chars().count() > MAX {
        format!("`{}…`", s.chars().take(MAX).collect::<String>())
    } else {
        format!("`{s}`")
    }
}

fn emit_unknown_kinds(md: &mut String, lockfile: &Lockfile) {
    for (kind, entries) in &lockfile.objects {
        if KNOWN_KINDS.contains(&kind.as_str()) || entries.is_empty() {
            continue;
        }
        md.push_str(&format!("## {kind}\n\n"));
        for (slug, entry) in entries {
            md.push_str(&entry_line(slug, entry.id, None));
            md.push('\n');
        }
        md.push('\n');
    }
}

// ----- Small helpers --------------------------------------------------

/// `` `slug` (id N) "Name" `` — the id is left out when unknown (0), the name
/// when the JSON is missing, unparseable, or has none.
fn entry_title(slug: &str, id: u64, v: Option<&Value>) -> String {
    let mut s = format!("`{slug}`");
    if id != 0 {
        s.push_str(&format!(" (id {id})"));
    }
    if let Some(name) = v
        .and_then(|v| v.get("name"))
        .and_then(Value::as_str)
        .filter(|n| !n.is_empty())
    {
        s.push_str(&format!(" {}", quote_for_md(name)));
    }
    s
}

fn entry_line(slug: &str, id: u64, v: Option<&Value>) -> String {
    format!("- {}", entry_title(slug, id, v))
}

fn read_json(path: &Path) -> Option<Value> {
    let raw = std::fs::read_to_string(path).ok()?;
    serde_json::from_str(&raw).ok()
}

fn url_to_slug<'a>(v: &Value, key: &str, kind: &str, lf: &'a Lockfile) -> Option<&'a str> {
    let url = v.get(key).and_then(|u| u.as_str())?;
    lf.slug_for_url(kind, url)
}

fn urls_to_slugs<'a>(v: &Value, key: &str, kind: &str, lf: &'a Lockfile) -> Vec<&'a str> {
    v.get(key)
        .and_then(|x| x.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|u| u.as_str())
                .filter_map(|u| lf.slug_for_url(kind, u))
                .collect()
        })
        .unwrap_or_default()
}

fn join_slugs(slugs: &[&str]) -> String {
    slugs
        .iter()
        .map(|s| format!("`{s}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Names of the subdirectories of `dir`, unsorted. Empty if `dir` is absent.
fn subdirs(dir: &Path) -> Vec<String> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    entries
        .flatten()
        .filter(|e| e.file_type().is_ok_and(|t| t.is_dir()))
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect()
}

/// Wrap a short human string in double quotes for markdown emission.
/// Truncates pathologically long names so the index stays scannable.
fn quote_for_md(s: &str) -> String {
    const MAX: usize = 120;
    let safe = s.replace(['\n', '\r'], " ");
    if safe.chars().count() > MAX {
        let head: String = safe.chars().take(MAX).collect();
        format!("\"{head}…\"")
    } else {
        format!("\"{safe}\"")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::ObjectEntry;

    fn entry(id: u64) -> ObjectEntry {
        ObjectEntry {
            id,
            modified_at: None,
            modified_by: None,
            content_hash: None,
            secrets_hash: None,
        }
    }

    fn index_of(paths: &Paths, lf: &Lockfile) -> String {
        generate(paths, lf).unwrap();
        std::fs::read_to_string(paths.env_root().join("_index.md")).unwrap()
    }

    #[test]
    fn header_carries_counts_and_only_the_path_rules_for_kinds_present() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        std::fs::create_dir_all(paths.env_root()).unwrap();

        let mut lf = Lockfile::default();
        lf.upsert("hooks", "validator", entry(1));
        lf.upsert("hooks", "exporter", entry(2));
        lf.upsert("rules", "validation", entry(3));

        let body = index_of(&paths, &lf);
        assert!(body.starts_with("<!-- generated by rdc; do not edit -->\n# dev\n"));
        assert!(body.contains("Objects: 2 hooks · 1 rules."), "{body}");
        assert!(body.contains("- hook: `envs/dev/hooks/<slug>.json`"), "{body}");
        assert!(body.contains("- rule: `envs/dev/rules/<slug>.json`"), "{body}");
        assert!(!body.contains("label:"), "no labels, so no label rule: {body}");
        assert!(body.contains("- `validator` (id 1)\n"), "{body}");
        assert!(body.contains("- `validation` (id 3)\n"), "{body}");
        assert!(body.ends_with(")\n") && !body.ends_with("\n\n"), "{body:?}");
    }

    #[test]
    fn generate_skips_when_env_root_missing() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "missing");
        let lf = Lockfile::default();
        generate(&paths, &lf).unwrap();
        assert!(!paths.env_root().exists());
    }

    #[test]
    fn hook_is_one_line_with_type_state_events_order_and_queues() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        std::fs::create_dir_all(paths.hooks_dir()).unwrap();
        std::fs::write(
            paths.hooks_dir().join("validator.json"),
            r#"{"id":1,"name":"Validator: invoices","type":"function","active":false,
               "events":["annotation_content.initialize","annotation_content.updated"],
               "run_after":["rdc://hooks/normalizer"],
               "queues":["rdc://queues/invoices","https://x/api/v1/queues/101"]}"#,
        )
        .unwrap();

        let mut lf = Lockfile::default();
        lf.upsert("hooks", "validator", entry(1));
        lf.upsert("hooks", "normalizer", entry(2));
        lf.upsert("queues", "invoices", entry(100));
        lf.upsert("queues", "credit-notes", entry(101));

        let body = index_of(&paths, &lf);
        assert!(
            body.contains(
                "- `validator` (id 1) \"Validator: invoices\" · function · **inactive** · \
                 on [annotation_content.initialize, annotation_content.updated] · \
                 after `normalizer` · queues `invoices`, `credit-notes`\n"
            ),
            "{body}"
        );
    }

    #[test]
    fn an_active_hook_is_not_marked() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        std::fs::create_dir_all(paths.hooks_dir()).unwrap();
        std::fs::write(
            paths.hooks_dir().join("a.json"),
            r#"{"id":1,"name":"A","type":"webhook","active":true}"#,
        )
        .unwrap();
        let mut lf = Lockfile::default();
        lf.upsert("hooks", "a", entry(1));
        let body = index_of(&paths, &lf);
        assert!(body.contains("- `a` (id 1) \"A\" · webhook\n"), "{body}");
    }

    #[test]
    fn queues_group_under_workspace_with_engine_and_folded_counts() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        let q_dir = paths.queue_dir("main", "invoices");
        std::fs::create_dir_all(q_dir.join("formulas")).unwrap();
        std::fs::write(
            paths.workspace_dir("main").join("workspace.json"),
            r#"{"id":700,"name":"Main"}"#,
        )
        .unwrap();
        std::fs::write(
            q_dir.join("queue.json"),
            r#"{"id":100,"name":"Invoices","engine":"rdc://engines/inv",
               "schema":"rdc://schemas/invoices","inbox":"rdc://inboxes/invoices"}"#,
        )
        .unwrap();
        std::fs::write(q_dir.join("formulas/amount_total.py"), b"a+b").unwrap();
        std::fs::write(q_dir.join("formulas/invoice_id.py"), b"x").unwrap();
        // A hook naming the queue: listed on the hook's line, not the queue's.
        std::fs::create_dir_all(paths.hooks_dir()).unwrap();
        std::fs::write(
            paths.hooks_dir().join("validator.json"),
            r#"{"id":1,"name":"V","queues":["rdc://queues/invoices"]}"#,
        )
        .unwrap();

        let mut lf = Lockfile::default();
        lf.upsert("workspaces", "main", entry(700));
        lf.upsert("workspaces", "empty", entry(701));
        lf.upsert("queues", "invoices", entry(100));
        lf.upsert("queues", "orphan", entry(102));
        lf.upsert("schemas", "invoices", entry(200));
        lf.upsert("inboxes", "invoices", entry(300));
        lf.upsert("engines", "inv", entry(3));
        lf.upsert("hooks", "validator", entry(1));
        lf.upsert("email_templates", "main/invoices/rejection", entry(5));

        let body = index_of(&paths, &lf);
        assert!(
            body.contains(
                "### `main` (id 700) \"Main\"\n\n\
                 - `invoices` (id 100) \"Invoices\" · engine `inv`\n"
            ),
            "{body}"
        );
        assert!(body.contains("### `empty` (id 701)\n\n### "), "{body}");
        assert!(body.contains("### not on disk\n\n- `orphan` (id 102)\n"), "{body}");
        // Folded kinds get no section of their own.
        for gone in ["## workspaces", "## schemas", "## inboxes", "## email_templates"] {
            assert!(!body.contains(gone), "{gone}: {body}");
        }
        // The reverse link is gone; the hook carries the only one.
        assert_eq!(body.matches("`invoices`").count(), 2, "queue line + hook line: {body}");
    }

    #[test]
    fn engine_fields_are_neither_listed_nor_counted() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        let fields = paths.engine_fields_dir("invoice");
        std::fs::create_dir_all(&fields).unwrap();
        std::fs::write(paths.engine_dir("invoice").join("engine.json"), r#"{"id":3,"name":"Invoice"}"#).unwrap();
        std::fs::write(fields.join("invoice-id.json"), b"{}").unwrap();
        std::fs::write(fields.join("total.json"), b"{}").unwrap();

        let mut lf = Lockfile::default();
        lf.upsert("engines", "invoice", entry(3));
        lf.upsert("engine_fields", "invoice/invoice-id", entry(11));
        lf.upsert("engine_fields", "invoice/total", entry(12));

        let body = index_of(&paths, &lf);
        assert!(body.contains("- `invoice` (id 3) \"Invoice\"\n"), "{body}");
        assert!(!body.contains("invoice-id"), "{body}");
        assert!(body.contains("Objects: 2 engine_fields · 1 engines."), "{body}");
    }

    #[test]
    fn workflow_lists_its_steps_in_order() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        std::fs::create_dir_all(paths.workflow_steps_dir("ap-flow")).unwrap();
        std::fs::write(
            paths.workflow_dir("ap-flow").join("workflow.json"),
            r#"{"id":5,"name":"AP Flow",
               "steps":["https://x/api/v1/workflow_steps/9","https://x/api/v1/workflow_steps/10"]}"#,
        )
        .unwrap();

        let mut lf = Lockfile::default();
        lf.upsert("workflows", "ap-flow", entry(5));
        lf.upsert("workflow_steps", "ap-flow/manager", entry(9));
        lf.upsert("workflow_steps", "ap-flow/finance", entry(10));

        let body = index_of(&paths, &lf);
        assert!(
            body.contains("- `ap-flow` (id 5) \"AP Flow\" · steps `ap-flow/manager`, `ap-flow/finance`\n"),
            "{body}"
        );
        assert!(!body.contains("## workflow_steps"), "{body}");
    }

    #[test]
    fn unparseable_json_falls_back_to_slug_and_id() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        std::fs::create_dir_all(paths.hooks_dir()).unwrap();
        std::fs::write(paths.hooks_dir().join("broken.json"), b"not valid json").unwrap();

        let mut lf = Lockfile::default();
        lf.upsert("hooks", "broken", entry(7));

        let body = index_of(&paths, &lf);
        assert!(body.contains("## hooks\n\n- `broken` (id 7)\n"), "{body:?}");
    }

    #[test]
    fn output_is_deterministic_across_runs() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        std::fs::create_dir_all(paths.queue_dir("ws-b", "q1")).unwrap();
        std::fs::create_dir_all(paths.queue_dir("ws-a", "q2")).unwrap();
        std::fs::create_dir_all(paths.hooks_dir()).unwrap();
        std::fs::write(paths.hooks_dir().join("a.json"), r#"{"id":1,"name":"A"}"#).unwrap();
        std::fs::write(paths.hooks_dir().join("b.json"), r#"{"id":2,"name":"B"}"#).unwrap();

        let mut lf = Lockfile::default();
        lf.upsert("hooks", "a", entry(1));
        lf.upsert("hooks", "b", entry(2));
        lf.upsert("queues", "q1", entry(10));
        lf.upsert("queues", "q2", entry(11));

        let body1 = index_of(&paths, &lf);
        let body2 = index_of(&paths, &lf);
        assert_eq!(body1, body2);
        // Workspaces sort by slug even when not in the lockfile.
        assert!(body1.find("`ws-a`").unwrap() < body1.find("`ws-b`").unwrap(), "{body1}");
    }

    #[test]
    fn name_with_newlines_or_huge_size_is_quoted_safely() {
        assert_eq!(quote_for_md("simple"), "\"simple\"");
        assert_eq!(quote_for_md("two\nlines"), "\"two lines\"");
        let long = "x".repeat(200);
        let q = quote_for_md(&long);
        assert!(q.ends_with("…\""));
        assert!(q.chars().count() <= 123, "truncated form should be bounded");
    }

    #[test]
    fn no_link_to_claude_md_which_is_already_loaded() {
        let dir = tempfile::TempDir::new().unwrap();
        std::fs::write(dir.path().join("CLAUDE.md"), b"agent guide").unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        std::fs::create_dir_all(paths.env_root()).unwrap();
        let body = index_of(&paths, &Lockfile::default());
        assert!(!body.contains("CLAUDE.md"), "{body}");
    }

    #[test]
    fn unknown_kinds_are_listed_terse() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        std::fs::create_dir_all(paths.env_root()).unwrap();
        let mut lf = Lockfile::default();
        lf.upsert("mdh_collections", "vendors", entry(0));
        let body = index_of(&paths, &lf);
        assert!(body.contains("## mdh_collections\n\n- `vendors`\n"), "{body}");
    }

    #[test]
    fn mdh_indexes_list_each_index_definition() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        std::fs::create_dir_all(paths.dataset_dir("vendors")).unwrap();
        std::fs::write(
            paths.dataset_dir("vendors").join("indexes.json"),
            r#"{
              "regular": [
                {"name": "ix_vendor_id", "key": {"vendor_id": 1}, "unique": true},
                {"name": "ix_name_country", "key": {"name": 1, "country": -1},
                 "partialFilterExpression": {"active": true}, "collation": {"locale": "en"}},
                {"name": "ix_text", "key": {"notes": "text"}, "sparse": true, "expireAfterSeconds": 3600}
              ],
              "search": [
                {"name": "default", "analyzer": "lucene.standard",
                 "mappings": {"dynamic": false, "fields": {
                   "name": [{"type": "string"}, {"type": "autocomplete"}],
                   "address": {"type": "document", "fields": {"city": {"type": "string"}}}
                 }},
                 "synonyms": [{"name": "names", "analyzer": "lucene.standard", "source": {"collection": "syn"}}]},
                {"name": "everything", "mappings": {"dynamic": true}}
              ]
            }"#,
        )
        .unwrap();

        let mut lf = Lockfile::default();
        lf.upsert("mdh_indexes", "vendors", entry(0));

        let body = index_of(&paths, &lf);
        assert!(
            body.contains(
                "## mdh_indexes\n\n- `vendors`\n\
                 \x20 - `ix_vendor_id`: `vendor_id` asc · unique\n\
                 \x20 - `ix_name_country`: `name` asc, `country` desc · partial `{\"active\":true}` · collation `en`\n\
                 \x20 - `ix_text`: `notes` text · sparse · expires after 3600s\n\
                 \x20 - search `default`: `name` string/autocomplete, `address.city` string · analyzer `lucene.standard` · synonyms `names`\n\
                 \x20 - search `everything` · dynamic\n"
            ),
            "{body}"
        );
        assert!(body.contains("`envs/dev/mdh/<dataset>/`, indexes in `indexes.json`"), "{body}");
    }

    #[test]
    fn mdh_dataset_without_indexes_file_is_listed_bare() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        std::fs::create_dir_all(paths.env_root()).unwrap();
        let mut lf = Lockfile::default();
        lf.upsert("mdh_indexes", "vendors", entry(0));
        let body = index_of(&paths, &lf);
        assert!(body.ends_with("## mdh_indexes\n\n- `vendors`\n"), "{body:?}");
    }
}
