use crate::paths::Paths;
use crate::state::Lockfile;
use anyhow::{Context, Result};

/// Generate `<env_root>/_index.md` from the lockfile contents.
/// The file starts with `<!-- generated by rdc; do not edit -->` so users know
/// to regenerate via `rdc pull` rather than editing by hand.
pub fn generate(paths: &Paths, lockfile: &Lockfile) -> Result<()> {
    let env_root = paths.env_root();
    if !env_root.exists() {
        return Ok(());
    }

    let mut md = String::new();
    md.push_str("<!-- generated by rdc; do not edit -->\n");
    md.push_str(&format!("# {}\n\n", paths.env()));
    md.push_str("This file is regenerated on every `rdc pull`. Edit the snapshot files, not this index.\n\n");
    md.push_str("## Inventory\n\n");

    let preferred = [
        "organization",
        "workspaces",
        "queues",
        "schemas",
        "inboxes",
        "hooks",
        "rules",
        "labels",
        "engines",
        "engine_fields",
        "workflows",
        "workflow_steps",
        "email_templates",
        "mdh_collections",
        "mdh_indexes",
    ];

    let mut emitted: std::collections::HashSet<&str> = std::collections::HashSet::new();
    for kind in preferred {
        if let Some(entries) = lockfile.objects.get(kind) {
            md.push_str(&format!("- {}: {}\n", kind, entries.len()));
            emitted.insert(kind);
        }
    }
    for (kind, entries) in lockfile.objects.iter() {
        if !emitted.contains(kind.as_str()) {
            md.push_str(&format!("- {}: {}\n", kind, entries.len()));
        }
    }
    md.push('\n');

    for kind in preferred {
        if let Some(entries) = lockfile.objects.get(kind) {
            md.push_str(&format!("## {}\n\n", kind));
            for (slug, entry) in entries.iter() {
                if entry.id == 0 {
                    md.push_str(&format!("- `{}`\n", slug));
                } else {
                    md.push_str(&format!("- `{}` (id {})\n", slug, entry.id));
                }
            }
            md.push('\n');
        }
    }

    let path = env_root.join("_index.md");
    crate::snapshot::writer::write_atomic(&path, md.as_bytes())
        .with_context(|| format!("writing {}", path.display()))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::ObjectEntry;

    #[test]
    fn generate_writes_index_file() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "dev");
        std::fs::create_dir_all(paths.env_root()).unwrap();

        let mut lf = Lockfile::default();
        lf.upsert("hooks", "validator", ObjectEntry {
            id: 1, url: None, modified_at: None, content_hash: None,
        });
        lf.upsert("hooks", "sftp-import", ObjectEntry {
            id: 2, url: None, modified_at: None, content_hash: None,
        });
        lf.upsert("rules", "validation", ObjectEntry {
            id: 3, url: None, modified_at: None, content_hash: None,
        });

        generate(&paths, &lf).unwrap();

        let body = std::fs::read_to_string(paths.env_root().join("_index.md")).unwrap();
        assert!(body.starts_with("<!-- generated by rdc; do not edit -->"));
        assert!(body.contains("# dev"));
        assert!(body.contains("- hooks: 2"));
        assert!(body.contains("- rules: 1"));
        assert!(body.contains("`validator` (id 1)"));
        assert!(body.contains("`sftp-import` (id 2)"));
        assert!(body.contains("`validation` (id 3)"));
    }

    #[test]
    fn generate_skips_when_env_root_missing() {
        let dir = tempfile::TempDir::new().unwrap();
        let paths = Paths::for_env(dir.path(), "missing");
        let lf = Lockfile::default();
        generate(&paths, &lf).unwrap();
        assert!(!paths.env_root().exists());
    }
}
