// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'rdc.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `block_on`, `env_api_base`, `policy_to_strategy`, `valid_env_name`, `write_credentials`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LineCollector`, `LineForwarder`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `flush`, `flush`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `write`, `write`

/// rdc's package version, surfaced to the app's About box.
Future<String?> rdcVersion() => RustLib.instance.api.crateApiRdcRdcVersion();

/// List every Project under `parent`. Non-project folders are skipped.
Future<List<ProjectSummary>> listProjects({required String parent}) =>
    RustLib.instance.api.crateApiRdcListProjects(parent: parent);

/// Create a new Project: write `rdc.toml` + secrets for a first env named by
/// the caller (`first_env.name`) under a unique slug. (Additional envs are
/// added later via `add_env`.)
Future<ProjectSummary> addProject({
  required String parent,
  required String projectName,
  required AddEnvInput firstEnv,
}) => RustLib.instance.api.crateApiRdcAddProject(
  parent: parent,
  projectName: projectName,
  firstEnv: firstEnv,
);

/// Validate that `path` is an rdc project (≥1 env, any names) and return its
/// summary. Does not move, copy, or symlink anything.
Future<ProjectSummary> validateExistingProject({required String path}) =>
    RustLib.instance.api.crateApiRdcValidateExistingProject(path: path);

/// Rename the project folder (from `input.name`) if it changed, and rewrite the
/// named `env`'s api_base/org_id through rdc's own config writer. Credentials
/// are only replaced when supplied (blank = keep existing).
Future<ProjectSummary> editProject({
  required String folder,
  required String env,
  required EditConnectionInput input,
}) => RustLib.instance.api.crateApiRdcEditProject(
  folder: folder,
  env: env,
  input: input,
);

/// Add a new environment to an existing project. Errors if the env already exists.
Future<ProjectSummary> addEnv({
  required String folder,
  required AddEnvInput input,
}) => RustLib.instance.api.crateApiRdcAddEnv(folder: folder, input: input);

/// Remove an environment: its `rdc.toml` section, snapshot, secrets, and state.
/// If it was the last env, the whole project is trashed and `Ok(None)` returned.
Future<ProjectSummary?> removeEnv({
  required String folder,
  required String env,
}) => RustLib.instance.api.crateApiRdcRemoveEnv(folder: folder, env: env);

/// Rename an environment `old` → `new` entirely locally: move every per-env
/// path, rewrite `.rdc/mapping.toml`, and rename the `[envs.<old>]` section.
Future<ProjectSummary> renameEnv({
  required String folder,
  required String old,
  required String new_,
}) => RustLib.instance.api.crateApiRdcRenameEnv(
  folder: folder,
  old: old,
  new_: new_,
);

/// Pull-only sync of one environment. Scaffolds init files, resolves the token
/// (silent re-login in password mode), then runs `sync_no_push`. Progress is
/// streamed as `SyncPhase`.
///
/// Returns `Ok(())` even when the sync itself fails — the terminal outcome
/// (success or error) is conveyed to the caller via the `SyncPhase::Done` /
/// `SyncPhase::Error` stream events, not via this function's `Result`.
Stream<SyncPhase> syncEnv({
  required String folder,
  required String env,
  required String apiBase,
  required BigInt orgId,
}) => RustLib.instance.api.crateApiRdcSyncEnv(
  folder: folder,
  env: env,
  apiBase: apiBase,
  orgId: orgId,
);

/// Offline `migrate src -> tgt` (writes local `envs/<tgt>/`), then a dry-run
/// `--no-pull` push whose rendered plan is captured and returned. Needs the
/// TARGET env's token (the dry-run push lists/scans the target remote to
/// compute the plan). Nothing is written to the remote.
Future<PromotionPreview> preparePromotion({
  required String folder,
  required String src,
  required String tgt,
  required bool mirror,
}) => RustLib.instance.api.crateApiRdcPreparePromotion(
  folder: folder,
  src: src,
  tgt: tgt,
  mirror: mirror,
);

/// The real gated push: re-runs the offline migrate (so the pushed snapshot
/// reflects `src` at push time, not whatever `prepare_promotion` saw earlier)
/// then a real `--no-pull` push with the chosen conflict policy and
/// allow-deletes, streaming the log. Needs the TARGET token.
Stream<SyncPhase> pushPromotion({
  required String folder,
  required String src,
  required String tgt,
  required bool mirror,
  required ConflictPolicy policy,
  required bool allowDeletes,
}) => RustLib.instance.api.crateApiRdcPushPromotion(
  folder: folder,
  src: src,
  tgt: tgt,
  mirror: mirror,
  policy: policy,
  allowDeletes: allowDeletes,
);

/// Move a managed Project's folder to the OS trash/recycle bin.
Future<void> trashProject({required String folder}) =>
    RustLib.instance.api.crateApiRdcTrashProject(folder: folder);

/// Reveal a path in the OS file manager (Finder / Explorer / file manager).
Future<void> revealInFileManager({required String path}) =>
    RustLib.instance.api.crateApiRdcRevealInFileManager(path: path);

class AddEnvInput {
  final String name;
  final String apiBase;
  final BigInt orgId;
  final AuthKind authKind;
  final String? token;
  final String? username;
  final String? password;

  const AddEnvInput({
    required this.name,
    required this.apiBase,
    required this.orgId,
    required this.authKind,
    this.token,
    this.username,
    this.password,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      apiBase.hashCode ^
      orgId.hashCode ^
      authKind.hashCode ^
      token.hashCode ^
      username.hashCode ^
      password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddEnvInput &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          apiBase == other.apiBase &&
          orgId == other.orgId &&
          authKind == other.authKind &&
          token == other.token &&
          username == other.username &&
          password == other.password;
}

enum AuthKind { token, password }

/// How a promote push resolves a `BothDiverged` conflict (a datapoint edited
/// on both the source snapshot being promoted and the live target since the
/// last sync). Dart-facing name only — the mapping onto rdc's own
/// [`rdc::cli::resolve::ConflictStrategy`] is inverted; see
/// [`policy_to_strategy`].
enum ConflictPolicy {
  /// The promoted (local, just-migrated) side wins.
  useIncoming,

  /// The target (remote, already-live) side wins.
  keepTarget,

  /// Leave the conflicting item untouched (shadow-file fallback).
  skip,
}

class EditConnectionInput {
  /// The connection name; if it changes, the folder is renamed.
  final String name;
  final String apiBase;
  final BigInt orgId;
  final AuthKind authKind;

  /// Credentials are optional on edit: leave all blank to keep the existing
  /// ones. Provide new values (matching `auth_kind`) to replace them.
  final String? token;
  final String? username;
  final String? password;

  const EditConnectionInput({
    required this.name,
    required this.apiBase,
    required this.orgId,
    required this.authKind,
    this.token,
    this.username,
    this.password,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      apiBase.hashCode ^
      orgId.hashCode ^
      authKind.hashCode ^
      token.hashCode ^
      username.hashCode ^
      password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditConnectionInput &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          apiBase == other.apiBase &&
          orgId == other.orgId &&
          authKind == other.authKind &&
          token == other.token &&
          username == other.username &&
          password == other.password;
}

class EnvSummary {
  final String name;
  final String apiBase;
  final BigInt orgId;
  final AuthKind authKind;
  final PlatformInt64? lastSyncUnix;
  final BigInt fileCount;

  const EnvSummary({
    required this.name,
    required this.apiBase,
    required this.orgId,
    required this.authKind,
    this.lastSyncUnix,
    required this.fileCount,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      apiBase.hashCode ^
      orgId.hashCode ^
      authKind.hashCode ^
      lastSyncUnix.hashCode ^
      fileCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnvSummary &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          apiBase == other.apiBase &&
          orgId == other.orgId &&
          authKind == other.authKind &&
          lastSyncUnix == other.lastSyncUnix &&
          fileCount == other.fileCount;
}

class ProjectSummary {
  final String id;
  final String name;
  final String folder;
  final List<EnvSummary> envs;

  const ProjectSummary({
    required this.id,
    required this.name,
    required this.folder,
    required this.envs,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ folder.hashCode ^ envs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          folder == other.folder &&
          envs == other.envs;
}

/// The rendered, captured dry-run push plan for a pending promotion — one
/// entry per line of rdc's normal plan output.
class PromotionPreview {
  final List<String> plan;

  const PromotionPreview({required this.plan});

  @override
  int get hashCode => plan.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PromotionPreview &&
          runtimeType == other.runtimeType &&
          plan == other.plan;
}

@freezed
sealed class SyncPhase with _$SyncPhase {
  const SyncPhase._();

  const factory SyncPhase.started() = SyncPhase_Started;

  /// One line of rdc's real, rendered sync log (plain text, no color).
  const factory SyncPhase.log({required String line}) = SyncPhase_Log;
  const factory SyncPhase.done({required BigInt fileCount}) = SyncPhase_Done;
  const factory SyncPhase.error({required String message}) = SyncPhase_Error;
}
