// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'rdc.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `block_on`, `write_credentials`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LineForwarder`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `flush`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `write`

/// rdc's package version, surfaced to the app's About box.
Future<String?> rdcVersion() => RustLib.instance.api.crateApiRdcRdcVersion();

/// List every Connection under `parent`. Non-project folders are skipped.
Future<List<ConnectionSummary>> listConnections({required String parent}) =>
    RustLib.instance.api.crateApiRdcListConnections(parent: parent);

/// Create a new Connection: write `rdc.toml` + secrets under a unique slug.
Future<ConnectionSummary> addConnection({
  required String parent,
  required AddConnectionInput input,
}) =>
    RustLib.instance.api.crateApiRdcAddConnection(parent: parent, input: input);

/// Validate that `path` is a single-env (`main`) rdc project and return its
/// summary. Does not move, copy, or symlink anything.
Future<ConnectionSummary> validateExistingProject({required String path}) =>
    RustLib.instance.api.crateApiRdcValidateExistingProject(path: path);

/// Update a Connection's settings, renaming its folder if the name changed.
/// `api_base`/`org_id` are rewritten through rdc's own config writer so the
/// file matches the CLI's format exactly. Credentials are only touched when
/// new ones are supplied (blank = keep existing). Returns the (possibly moved)
/// Connection so the caller can reselect it.
Future<ConnectionSummary> editConnection({
  required String folder,
  required EditConnectionInput input,
}) => RustLib.instance.api.crateApiRdcEditConnection(
  folder: folder,
  input: input,
);

/// Pull-only sync of one Connection. Scaffolds init files, resolves the token
/// (silent re-login in password mode), then runs `sync_no_push`. Progress is
/// streamed as `SyncPhase`; the stream conveys the terminal outcome (Done or
/// Error) rather than throwing.
Stream<SyncPhase> syncConnection({
  required String folder,
  required String apiBase,
  required BigInt orgId,
}) => RustLib.instance.api.crateApiRdcSyncConnection(
  folder: folder,
  apiBase: apiBase,
  orgId: orgId,
);

/// Move a managed Connection's folder to the OS trash/recycle bin.
Future<void> trashConnection({required String folder}) =>
    RustLib.instance.api.crateApiRdcTrashConnection(folder: folder);

/// Reveal a path in the OS file manager (Finder / Explorer / file manager).
Future<void> revealInFileManager({required String path}) =>
    RustLib.instance.api.crateApiRdcRevealInFileManager(path: path);

class AddConnectionInput {
  final String name;
  final String apiBase;
  final BigInt orgId;
  final AuthKind authKind;
  final String? token;
  final String? username;
  final String? password;

  const AddConnectionInput({
    required this.name,
    required this.apiBase,
    required this.orgId,
    required this.authKind,
    this.token,
    this.username,
    this.password,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      apiBase.hashCode ^
      orgId.hashCode ^
      authKind.hashCode ^
      token.hashCode ^
      username.hashCode ^
      password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddConnectionInput &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          apiBase == other.apiBase &&
          orgId == other.orgId &&
          authKind == other.authKind &&
          token == other.token &&
          username == other.username &&
          password == other.password;
}

enum AuthKind { token, password }

class ConnectionSummary {
  final String id;
  final String name;
  final String apiBase;
  final BigInt orgId;
  final String folder;
  final AuthKind authKind;
  final PlatformInt64? lastSyncUnix;
  final BigInt fileCount;

  const ConnectionSummary({
    required this.id,
    required this.name,
    required this.apiBase,
    required this.orgId,
    required this.folder,
    required this.authKind,
    this.lastSyncUnix,
    required this.fileCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      apiBase.hashCode ^
      orgId.hashCode ^
      folder.hashCode ^
      authKind.hashCode ^
      lastSyncUnix.hashCode ^
      fileCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          apiBase == other.apiBase &&
          orgId == other.orgId &&
          folder == other.folder &&
          authKind == other.authKind &&
          lastSyncUnix == other.lastSyncUnix &&
          fileCount == other.fileCount;
}

class EditConnectionInput {
  /// The connection name; if it changes, the folder is renamed.
  final String name;
  final String apiBase;
  final BigInt orgId;
  final AuthKind authKind;

  /// Credentials are optional on edit: leave all blank to keep the existing
  /// ones. Provide new values (matching `auth_kind`) to replace them.
  final String? token;
  final String? username;
  final String? password;

  const EditConnectionInput({
    required this.name,
    required this.apiBase,
    required this.orgId,
    required this.authKind,
    this.token,
    this.username,
    this.password,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      apiBase.hashCode ^
      orgId.hashCode ^
      authKind.hashCode ^
      token.hashCode ^
      username.hashCode ^
      password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditConnectionInput &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          apiBase == other.apiBase &&
          orgId == other.orgId &&
          authKind == other.authKind &&
          token == other.token &&
          username == other.username &&
          password == other.password;
}

@freezed
sealed class SyncPhase with _$SyncPhase {
  const SyncPhase._();

  const factory SyncPhase.started() = SyncPhase_Started;

  /// One line of rdc's real, rendered sync log (plain text, no color).
  const factory SyncPhase.log({required String line}) = SyncPhase_Log;
  const factory SyncPhase.done({required BigInt fileCount}) = SyncPhase_Done;
  const factory SyncPhase.error({required String message}) = SyncPhase_Error;
}
