// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'rdc.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `block_on`, `discard`, `kind_to_dto`, `valid_env_name`, `write_credentials`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LineBuffer`, `LineForwarder`, `SinkPromptRoute`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `ask`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `flush`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `write`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `emit`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// rdc's package version, surfaced to the app's About box.
Future<String?> rdcVersion() => RustLib.instance.api.crateApiRdcRdcVersion();

/// List every Project under `parent`. Non-project folders are skipped.
Future<List<ProjectSummary>> listProjects({required String parent}) =>
    RustLib.instance.api.crateApiRdcListProjects(parent: parent);

/// Create a new Project: write `rdc.toml` + secrets for a first env named by
/// the caller (`first_env.name`) under a unique slug. (Additional envs are
/// added later via `add_env`.)
Future<ProjectSummary> addProject({
  required String parent,
  required String projectName,
  required AddEnvInput firstEnv,
}) => RustLib.instance.api.crateApiRdcAddProject(
  parent: parent,
  projectName: projectName,
  firstEnv: firstEnv,
);

/// Validate that `path` is an rdc project (≥1 env, any names) and return its
/// summary. Does not move, copy, or symlink anything.
Future<ProjectSummary> validateExistingProject({required String path}) =>
    RustLib.instance.api.crateApiRdcValidateExistingProject(path: path);

/// Rename the project folder (from `input.name`) if it changed, and rewrite the
/// named `env`'s api_base/org_id through rdc's own config writer. Credentials
/// are only replaced when supplied (blank = keep existing).
Future<ProjectSummary> editProject({
  required String folder,
  required String env,
  required EditConnectionInput input,
}) => RustLib.instance.api.crateApiRdcEditProject(
  folder: folder,
  env: env,
  input: input,
);

/// Add a new environment to an existing project. Errors if the env already exists.
Future<ProjectSummary> addEnv({
  required String folder,
  required AddEnvInput input,
}) => RustLib.instance.api.crateApiRdcAddEnv(folder: folder, input: input);

/// Remove an environment: its `rdc.toml` section, snapshot, secrets, and state.
/// If it was the last env, the whole project is trashed and `Ok(None)` returned.
Future<ProjectSummary?> removeEnv({
  required String folder,
  required String env,
}) => RustLib.instance.api.crateApiRdcRemoveEnv(folder: folder, env: env);

/// Rename an environment `old` → `new` entirely locally: move every per-env
/// path, rewrite `.rdc/mapping.toml`, and rename the `[envs.<old>]` section.
///
/// Not fully transactional: the state/conflicts moves below stay best-effort
/// (as before), but once the substantive moves (`env_root`, `secrets`) have
/// happened, a later failure (mapping.toml rewrite, final `rdc.toml` save)
/// triggers a best-effort rollback of exactly those substantive moves before
/// the error is returned, so the registry and filesystem don't end up
/// disagreeing (`rdc.toml` still naming `old` while the files live under
/// `new`, or vice versa).
Future<ProjectSummary> renameEnv({
  required String folder,
  required String old,
  required String new_,
}) => RustLib.instance.api.crateApiRdcRenameEnv(
  folder: folder,
  old: old,
  new_: new_,
);

/// Two-way sync of one environment. Scaffolds init files, resolves the token
/// (silent re-login in password mode), then runs one reconciliation cycle
/// under `EmbedSyncOptions::default()` (pull and push, prompting on a gate
/// rather than bailing). Progress is streamed as `SyncPhase`.
///
/// Returns `Ok(())` even when the sync itself fails — the terminal outcome
/// (success or error) is conveyed to the caller via the `SyncPhase::Done` /
/// `SyncPhase::Error` stream events, not via this function's `Result`.
Stream<SyncPhase> syncEnv({
  required String folder,
  required String env,
  required String apiBase,
  required BigInt orgId,
}) => RustLib.instance.api.crateApiRdcSyncEnv(
  folder: folder,
  env: env,
  apiBase: apiBase,
  orgId: orgId,
);

/// Watch one environment: reconcile once, then re-reconcile on a local file
/// change or on the poll timer, until `stop_watch` is called.
///
/// Blocks the calling FRB pool thread for the watch's whole life (the pool
/// is `num_cpus::get()` threads, so a great many concurrent watches would
/// starve other bridge calls). Progress, prompts and the between-cycle
/// countdown all arrive on `sink`.
///
/// Returns `Ok(())` even when the watch fails: the terminal outcome reaches
/// the caller as `SyncPhase::Error` / `SyncPhase::Stopped`, matching
/// `sync_env`'s contract.
Stream<SyncPhase> watchEnv({
  required String folder,
  required String env,
  required String apiBase,
  required BigInt orgId,
  BigInt? pollSecs,
}) => RustLib.instance.api.crateApiRdcWatchEnv(
  folder: folder,
  env: env,
  apiBase: apiBase,
  orgId: orgId,
  pollSecs: pollSecs,
);

/// Ask a running watch to stop. Also unblocks a cycle currently parked on a
/// prompt (`SinkPromptRoute::ask` polls this same token): the poll loop
/// reads the cancellation as end-of-input, exactly like a closed UI stream.
/// No-op if that env is not being watched.
Future<void> stopWatch({required String folder, required String env}) =>
    RustLib.instance.api.crateApiRdcStopWatch(folder: folder, env: env);

/// Answer the prompt a watch (or a one-shot sync) is currently blocked on.
/// `prompt_id` must be the id of the `SyncPhase::Prompt` being answered —
/// `SinkPromptRoute::ask` accepts an answer only when it matches the
/// question it is currently asking, so a mis-delivered or stale answer (a
/// UI race, a leftover call from a prompt that has already moved on) is
/// ignored rather than applied to the wrong question. On a path whose
/// answer can authorise deleting objects from a live organization, that
/// check is load-bearing, not defensive polish.
///
/// No-op if nothing on that env is waiting — an answer for a prompt that
/// has already been torn down is dropped, not queued.
Future<void> answerPrompt({
  required String folder,
  required String env,
  required BigInt promptId,
  required String answer,
}) => RustLib.instance.api.crateApiRdcAnswerPrompt(
  folder: folder,
  env: env,
  promptId: promptId,
  answer: answer,
);

/// Move a managed Project's folder to the OS trash/recycle bin.
Future<void> trashProject({required String folder}) =>
    RustLib.instance.api.crateApiRdcTrashProject(folder: folder);

/// Reveal a path in the OS file manager (Finder / Explorer / file manager).
Future<void> revealInFileManager({required String path}) =>
    RustLib.instance.api.crateApiRdcRevealInFileManager(path: path);

abstract class PromptSink {
  /// Send one phase. `false` means the UI side is gone (closed stream).
  Future<bool> emit({required SyncPhase phase});
}

class AddEnvInput {
  final String name;
  final String apiBase;
  final BigInt orgId;
  final AuthKind authKind;
  final String? token;
  final String? username;
  final String? password;

  const AddEnvInput({
    required this.name,
    required this.apiBase,
    required this.orgId,
    required this.authKind,
    this.token,
    this.username,
    this.password,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      apiBase.hashCode ^
      orgId.hashCode ^
      authKind.hashCode ^
      token.hashCode ^
      username.hashCode ^
      password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddEnvInput &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          apiBase == other.apiBase &&
          orgId == other.orgId &&
          authKind == other.authKind &&
          token == other.token &&
          username == other.username &&
          password == other.password;
}

enum AuthKind { token, password }

class EditConnectionInput {
  /// The connection name; if it changes, the folder is renamed.
  final String name;
  final String apiBase;
  final BigInt orgId;
  final AuthKind authKind;

  /// Credentials are optional on edit: leave all blank to keep the existing
  /// ones. Provide new values (matching `auth_kind`) to replace them.
  final String? token;
  final String? username;
  final String? password;

  const EditConnectionInput({
    required this.name,
    required this.apiBase,
    required this.orgId,
    required this.authKind,
    this.token,
    this.username,
    this.password,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      apiBase.hashCode ^
      orgId.hashCode ^
      authKind.hashCode ^
      token.hashCode ^
      username.hashCode ^
      password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditConnectionInput &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          apiBase == other.apiBase &&
          orgId == other.orgId &&
          authKind == other.authKind &&
          token == other.token &&
          username == other.username &&
          password == other.password;
}

class EnvSummary {
  final String name;
  final String apiBase;
  final BigInt orgId;
  final AuthKind authKind;
  final PlatformInt64? lastSyncUnix;
  final BigInt fileCount;

  const EnvSummary({
    required this.name,
    required this.apiBase,
    required this.orgId,
    required this.authKind,
    this.lastSyncUnix,
    required this.fileCount,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      apiBase.hashCode ^
      orgId.hashCode ^
      authKind.hashCode ^
      lastSyncUnix.hashCode ^
      fileCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnvSummary &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          apiBase == other.apiBase &&
          orgId == other.orgId &&
          authKind == other.authKind &&
          lastSyncUnix == other.lastSyncUnix &&
          fileCount == other.fileCount;
}

class ProjectSummary {
  final String id;
  final String name;
  final String folder;
  final List<EnvSummary> envs;

  const ProjectSummary({
    required this.id,
    required this.name,
    required this.folder,
    required this.envs,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ folder.hashCode ^ envs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          folder == other.folder &&
          envs == other.envs;
}

/// One answerable choice, as offered to the UI. `key` is a String rather
/// than a char because FRB has no char; it is always exactly one character.
class PromptChoice {
  final String key;
  final String label;

  const PromptChoice({required this.key, required this.label});

  @override
  int get hashCode => key.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PromptChoice &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label;
}

/// Mirrors `rdc::cli::stdin_coord::PromptKind` across the bridge.
enum PromptKindDto {
  conflict,
  remoteDelete,
  bulkConfirm,
  deleteGate,
  deleteDrift,
  mdhIndexDrop,
  mdhRowDelete,

  /// A coordinated read whose site never announced. Should be unreachable;
  /// it exists so that if it ever happens the UI can say so instead of
  /// silently mislabelling the prompt as a conflict. Render it as an
  /// explicit "unrecognised prompt" state, not as a normal dialog.
  unknown,
}

@freezed
sealed class SyncPhase with _$SyncPhase {
  const SyncPhase._();

  const factory SyncPhase.started() = SyncPhase_Started;

  /// One line of rdc's real, rendered sync log (plain text, no color).
  const factory SyncPhase.log({required String line}) = SyncPhase_Log;

  /// A cycle is blocked waiting for an answer. Reply with `answer_prompt`
  /// using this `id`. The diff/list this refers to has already arrived as
  /// `Log` lines.
  const factory SyncPhase.prompt({
    required BigInt id,
    required PromptKindDto kind,
    required String question,
    required List<PromptChoice> keys,
  }) = SyncPhase_Prompt;

  /// The prompt with this id no longer needs an answer (the watch stopped,
  /// or the cycle was torn down). Close the dialog.
  const factory SyncPhase.promptResolved({required BigInt id}) =
      SyncPhase_PromptResolved;

  /// A watch is between cycles. `next_poll_secs` is None when polling is
  /// disabled. rdc's own countdown never reaches an embedder — its
  /// in-place status line is a no-op off a TTY — so the app draws its own.
  const factory SyncPhase.idle({BigInt? nextPollSecs}) = SyncPhase_Idle;
  const factory SyncPhase.done({required BigInt fileCount}) = SyncPhase_Done;
  const factory SyncPhase.error({required String message}) = SyncPhase_Error;
  const factory SyncPhase.stopped() = SyncPhase_Stopped;
}
