// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/rdc.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiRdcInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 2140695709;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rdc_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ConnectionSummary> crateApiRdcAddConnection({
    required String parent,
    required AddConnectionInput input,
  });

  Future<ConnectionSummary> crateApiRdcEditConnection({
    required String folder,
    required EditConnectionInput input,
  });

  Future<void> crateApiRdcInitApp();

  Future<List<ConnectionSummary>> crateApiRdcListConnections({
    required String parent,
  });

  Future<String?> crateApiRdcRdcVersion();

  Future<void> crateApiRdcRevealInFileManager({required String path});

  Stream<SyncPhase> crateApiRdcSyncConnection({
    required String folder,
    required String apiBase,
    required BigInt orgId,
  });

  Future<void> crateApiRdcTrashConnection({required String folder});

  Future<ConnectionSummary> crateApiRdcValidateExistingProject({
    required String path,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ConnectionSummary> crateApiRdcAddConnection({
    required String parent,
    required AddConnectionInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(parent, serializer);
          sse_encode_box_autoadd_add_connection_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdcAddConnectionConstMeta,
        argValues: [parent, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdcAddConnectionConstMeta => const TaskConstMeta(
    debugName: "add_connection",
    argNames: ["parent", "input"],
  );

  @override
  Future<ConnectionSummary> crateApiRdcEditConnection({
    required String folder,
    required EditConnectionInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(folder, serializer);
          sse_encode_box_autoadd_edit_connection_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdcEditConnectionConstMeta,
        argValues: [folder, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdcEditConnectionConstMeta => const TaskConstMeta(
    debugName: "edit_connection",
    argNames: ["folder", "input"],
  );

  @override
  Future<void> crateApiRdcInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRdcInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdcInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<ConnectionSummary>> crateApiRdcListConnections({
    required String parent,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(parent, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_connection_summary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRdcListConnectionsConstMeta,
        argValues: [parent],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdcListConnectionsConstMeta =>
      const TaskConstMeta(debugName: "list_connections", argNames: ["parent"]);

  @override
  Future<String?> crateApiRdcRdcVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRdcRdcVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdcRdcVersionConstMeta =>
      const TaskConstMeta(debugName: "rdc_version", argNames: []);

  @override
  Future<void> crateApiRdcRevealInFileManager({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdcRevealInFileManagerConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdcRevealInFileManagerConstMeta =>
      const TaskConstMeta(
        debugName: "reveal_in_file_manager",
        argNames: ["path"],
      );

  @override
  Stream<SyncPhase> crateApiRdcSyncConnection({
    required String folder,
    required String apiBase,
    required BigInt orgId,
  }) {
    final sink = RustStreamSink<SyncPhase>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(folder, serializer);
            sse_encode_String(apiBase, serializer);
            sse_encode_u_64(orgId, serializer);
            sse_encode_StreamSink_sync_phase_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiRdcSyncConnectionConstMeta,
          argValues: [folder, apiBase, orgId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiRdcSyncConnectionConstMeta => const TaskConstMeta(
    debugName: "sync_connection",
    argNames: ["folder", "apiBase", "orgId", "sink"],
  );

  @override
  Future<void> crateApiRdcTrashConnection({required String folder}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(folder, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdcTrashConnectionConstMeta,
        argValues: [folder],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdcTrashConnectionConstMeta =>
      const TaskConstMeta(debugName: "trash_connection", argNames: ["folder"]);

  @override
  Future<ConnectionSummary> crateApiRdcValidateExistingProject({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdcValidateExistingProjectConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdcValidateExistingProjectConstMeta =>
      const TaskConstMeta(
        debugName: "validate_existing_project",
        argNames: ["path"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<SyncPhase> dco_decode_StreamSink_sync_phase_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AddConnectionInput dco_decode_add_connection_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AddConnectionInput(
      name: dco_decode_String(arr[0]),
      apiBase: dco_decode_String(arr[1]),
      orgId: dco_decode_u_64(arr[2]),
      authKind: dco_decode_auth_kind(arr[3]),
      token: dco_decode_opt_String(arr[4]),
      username: dco_decode_opt_String(arr[5]),
      password: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  AuthKind dco_decode_auth_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AuthKind.values[raw as int];
  }

  @protected
  AddConnectionInput dco_decode_box_autoadd_add_connection_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_add_connection_input(raw);
  }

  @protected
  EditConnectionInput dco_decode_box_autoadd_edit_connection_input(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_edit_connection_input(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  ConnectionSummary dco_decode_connection_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ConnectionSummary(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      apiBase: dco_decode_String(arr[2]),
      orgId: dco_decode_u_64(arr[3]),
      folder: dco_decode_String(arr[4]),
      authKind: dco_decode_auth_kind(arr[5]),
      lastSyncUnix: dco_decode_opt_box_autoadd_i_64(arr[6]),
      fileCount: dco_decode_u_64(arr[7]),
    );
  }

  @protected
  EditConnectionInput dco_decode_edit_connection_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return EditConnectionInput(
      name: dco_decode_String(arr[0]),
      apiBase: dco_decode_String(arr[1]),
      orgId: dco_decode_u_64(arr[2]),
      authKind: dco_decode_auth_kind(arr[3]),
      token: dco_decode_opt_String(arr[4]),
      username: dco_decode_opt_String(arr[5]),
      password: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<ConnectionSummary> dco_decode_list_connection_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_connection_summary).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  SyncPhase dco_decode_sync_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return SyncPhase_Started();
      case 1:
        return SyncPhase_Done(fileCount: dco_decode_u_64(raw[1]));
      case 2:
        return SyncPhase_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<SyncPhase> sse_decode_StreamSink_sync_phase_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AddConnectionInput sse_decode_add_connection_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_apiBase = sse_decode_String(deserializer);
    var var_orgId = sse_decode_u_64(deserializer);
    var var_authKind = sse_decode_auth_kind(deserializer);
    var var_token = sse_decode_opt_String(deserializer);
    var var_username = sse_decode_opt_String(deserializer);
    var var_password = sse_decode_opt_String(deserializer);
    return AddConnectionInput(
      name: var_name,
      apiBase: var_apiBase,
      orgId: var_orgId,
      authKind: var_authKind,
      token: var_token,
      username: var_username,
      password: var_password,
    );
  }

  @protected
  AuthKind sse_decode_auth_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AuthKind.values[inner];
  }

  @protected
  AddConnectionInput sse_decode_box_autoadd_add_connection_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_add_connection_input(deserializer));
  }

  @protected
  EditConnectionInput sse_decode_box_autoadd_edit_connection_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_edit_connection_input(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  ConnectionSummary sse_decode_connection_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_apiBase = sse_decode_String(deserializer);
    var var_orgId = sse_decode_u_64(deserializer);
    var var_folder = sse_decode_String(deserializer);
    var var_authKind = sse_decode_auth_kind(deserializer);
    var var_lastSyncUnix = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_fileCount = sse_decode_u_64(deserializer);
    return ConnectionSummary(
      id: var_id,
      name: var_name,
      apiBase: var_apiBase,
      orgId: var_orgId,
      folder: var_folder,
      authKind: var_authKind,
      lastSyncUnix: var_lastSyncUnix,
      fileCount: var_fileCount,
    );
  }

  @protected
  EditConnectionInput sse_decode_edit_connection_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_apiBase = sse_decode_String(deserializer);
    var var_orgId = sse_decode_u_64(deserializer);
    var var_authKind = sse_decode_auth_kind(deserializer);
    var var_token = sse_decode_opt_String(deserializer);
    var var_username = sse_decode_opt_String(deserializer);
    var var_password = sse_decode_opt_String(deserializer);
    return EditConnectionInput(
      name: var_name,
      apiBase: var_apiBase,
      orgId: var_orgId,
      authKind: var_authKind,
      token: var_token,
      username: var_username,
      password: var_password,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<ConnectionSummary> sse_decode_list_connection_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConnectionSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_connection_summary(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SyncPhase sse_decode_sync_phase(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return SyncPhase_Started();
      case 1:
        var var_fileCount = sse_decode_u_64(deserializer);
        return SyncPhase_Done(fileCount: var_fileCount);
      case 2:
        var var_message = sse_decode_String(deserializer);
        return SyncPhase_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_sync_phase_Sse(
    RustStreamSink<SyncPhase> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_phase,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_add_connection_input(
    AddConnectionInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.apiBase, serializer);
    sse_encode_u_64(self.orgId, serializer);
    sse_encode_auth_kind(self.authKind, serializer);
    sse_encode_opt_String(self.token, serializer);
    sse_encode_opt_String(self.username, serializer);
    sse_encode_opt_String(self.password, serializer);
  }

  @protected
  void sse_encode_auth_kind(AuthKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_box_autoadd_add_connection_input(
    AddConnectionInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_add_connection_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_edit_connection_input(
    EditConnectionInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_edit_connection_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_connection_summary(
    ConnectionSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.apiBase, serializer);
    sse_encode_u_64(self.orgId, serializer);
    sse_encode_String(self.folder, serializer);
    sse_encode_auth_kind(self.authKind, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastSyncUnix, serializer);
    sse_encode_u_64(self.fileCount, serializer);
  }

  @protected
  void sse_encode_edit_connection_input(
    EditConnectionInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.apiBase, serializer);
    sse_encode_u_64(self.orgId, serializer);
    sse_encode_auth_kind(self.authKind, serializer);
    sse_encode_opt_String(self.token, serializer);
    sse_encode_opt_String(self.username, serializer);
    sse_encode_opt_String(self.password, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_connection_summary(
    List<ConnectionSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_connection_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_sync_phase(SyncPhase self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case SyncPhase_Started():
        sse_encode_i_32(0, serializer);
      case SyncPhase_Done(fileCount: final fileCount):
        sse_encode_i_32(1, serializer);
        sse_encode_u_64(fileCount, serializer);
      case SyncPhase_Error(message: final message):
        sse_encode_i_32(2, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
