// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/rdc.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<SyncPhase> dco_decode_StreamSink_sync_phase_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddEnvInput dco_decode_add_env_input(dynamic raw);

  @protected
  AuthKind dco_decode_auth_kind(dynamic raw);

  @protected
  AddEnvInput dco_decode_box_autoadd_add_env_input(dynamic raw);

  @protected
  EditConnectionInput dco_decode_box_autoadd_edit_connection_input(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ProjectSummary dco_decode_box_autoadd_project_summary(dynamic raw);

  @protected
  EditConnectionInput dco_decode_edit_connection_input(dynamic raw);

  @protected
  EnvSummary dco_decode_env_summary(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<EnvSummary> dco_decode_list_env_summary(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProjectSummary> dco_decode_list_project_summary(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ProjectSummary? dco_decode_opt_box_autoadd_project_summary(dynamic raw);

  @protected
  ProjectSummary dco_decode_project_summary(dynamic raw);

  @protected
  SyncPhase dco_decode_sync_phase(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<SyncPhase> sse_decode_StreamSink_sync_phase_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddEnvInput sse_decode_add_env_input(SseDeserializer deserializer);

  @protected
  AuthKind sse_decode_auth_kind(SseDeserializer deserializer);

  @protected
  AddEnvInput sse_decode_box_autoadd_add_env_input(
    SseDeserializer deserializer,
  );

  @protected
  EditConnectionInput sse_decode_box_autoadd_edit_connection_input(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ProjectSummary sse_decode_box_autoadd_project_summary(
    SseDeserializer deserializer,
  );

  @protected
  EditConnectionInput sse_decode_edit_connection_input(
    SseDeserializer deserializer,
  );

  @protected
  EnvSummary sse_decode_env_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<EnvSummary> sse_decode_list_env_summary(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProjectSummary> sse_decode_list_project_summary(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ProjectSummary? sse_decode_opt_box_autoadd_project_summary(
    SseDeserializer deserializer,
  );

  @protected
  ProjectSummary sse_decode_project_summary(SseDeserializer deserializer);

  @protected
  SyncPhase sse_decode_sync_phase(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_phase_Sse(
    RustStreamSink<SyncPhase> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_add_env_input(AddEnvInput self, SseSerializer serializer);

  @protected
  void sse_encode_auth_kind(AuthKind self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_env_input(
    AddEnvInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_edit_connection_input(
    EditConnectionInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_project_summary(
    ProjectSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_edit_connection_input(
    EditConnectionInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_env_summary(EnvSummary self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_env_summary(
    List<EnvSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_summary(
    List<ProjectSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_project_summary(
    ProjectSummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_summary(
    ProjectSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_phase(SyncPhase self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
